### ISSUE TITLE
refresh <tablename> since max(sys_updated_on)

### ISSUE THREAD

**Issue by cruscio** [gflewis/sndml#8]
What do you think of a method to refresh based on the latest timestamp in the datamart destination table: ```refresh <tablename> since latest``` where `latest` is calculated at runtime by selecting `max(sys_updated_on)` from the destination table being refreshed. 

This would allow an execution of a refresh to dynamically calculate the interval of time necessary to extract new inserts/updates, regardless of when the last successful refresh occurred (though to be safe, it would require datamart upserts to occur in order, in case a run fails in the middle of a batch)

**Comment by gflewis** [comment]
Incremental updates (since the last run) will be supported in version 3.0 as follows:

SNDML3 can write a metrics file which contains, among other things, the start time of the run. The metrics file can also be read at the start of the next run, allowing SNDML3 to process all records inserted or updated since the last run.  This is described here:
https://github.com/gflewis/sndml3/wiki/Incremental-loads-using-a-metrics-file

SNDML3 is still unstable, but it should be ready for beta testing later this month. I’ll let you know as soon as it is. 

SNDML3 is a pretty much a complete rewrite of the app. The SOAP API has been replaced with REST for improved performance. The “script” file is replaced with a YAML configuration file. The code has been completely refactored and is much cleaner overall.

**Comment by gflewis** [comment]
Marking this issue "closed". Please test out the incremental load functionality in sndml3, and open a new issue in the sndml3 project if you encounter any issues. Thanks.
